### ISSUE TITLE
"TypeError: node.credsNode.addEventListener is not a function"

### ISSUE THREAD

**Issue by Eextol** [recursivecodes/node-red-contrib-ring-central#1]
"TypeError: node.credsNode.addEventListener is not a function"

This error appears and prevents the nodes from working.  I have tried on a couple different devices and Node-Red versions, same result each time.

30 Sep 09:12:02 - [info] Node-RED version: v1.0.6
30 Sep 09:12:02 - [info] Node.js  version: v12.16.2
30 Sep 09:12:02 - [info] Windows_NT 10.0.18363 x64 LE

30 Sep 09:48:29 - [error] [rc-credentials:OSA SMS App] Error: Resource not found
30 Sep 09:48:38 - [error] [sms-send:c8966955.579d68] TypeError: node.credsNode.addEventListener is not a function
30 Sep 09:56:59 - [error] [sms-send:c8966955.579d68] TypeError: node.credsNode.addEventListener is not a function
30 Sep 10:02:05 - [error] [sms-send:c8966955.579d68] TypeError: node.credsNode.addEventListener is not a function
30 Sep 10:05:13 - [warn]

Any help would be appreciated.

**Comment by EJJCSJ** [comment]
I'm having the same problem.....have you got a fix?

I'm a bit of a noob so any assist is greatly appreciated

**Comment by Eextol** [comment]
No sorry, I am also a noob and made no progress.

**Comment by EJJCSJ** [comment]
I'm trying to get more info from RingCentral - I'll post here if I can get it working....

**Comment by EJJCSJ** [comment]
Looks like RingCentral is not for me - I'm in the UK and it doesn't support international SMS....bugger!!!

This might only be a sandbox issue...but I'm not gonna fork out good money for a free messaging system....

I'll keep trying

**Comment by Eextol** [comment]
https://www.youtube.com/watch?v=sqyFAx_OlTM

From the comments on the video "You need to activate the password in Sandbox."

This worked for me
